### ISSUE TITLE
页面有一些例如gulp、fis的编译处理吗？

### ISSUE THREAD

**Issue by jincdream** [laispace/pager#2]
例如合并图片，
编译sass

**Comment by laispace** [comment]
@jincdream 还没加噢，目前这是个原型，很多都没做，包括压缩。

我是不是太早放出来了。。。

**Comment by jincdream** [comment]
你可以提供个开发文档，让大家一起开发？~ O(∩_∩)O~

**Comment by laispace** [comment]
@jincdream 哈哈 好啊，等我把我想做的基础功能做好了整理个文档出来
