### ISSUE TITLE
遇到个问题，装好环境后，执行npm run start之后没有报错，浏览器弹出localhost:3000之后就一直访问不了，请问这是什么原因呢？

### ISSUE THREAD

**Issue by jiangjiang01** [laispace/pager#3]

**Comment by laispace** [comment]
你开启数据库了么？

**Comment by haiyangJ** [comment]
是我访问地址的问题，应该使用localhost:5000访问
![image](https://cloud.githubusercontent.com/assets/16829509/14379315/2a8510cc-fdac-11e5-896d-dc427feb991b.png)

**Comment by jiangjiang01** [comment]
数据库应该是正确开启了，刚才用localhost:5000访问过一次，然后就访问不了了。localhost:3000一直都访问不了，很奇怪

**Comment by laispace** [comment]
换 127.0.0.1:3000 试试

**Comment by nupthale** [comment]
是因为文档写错了， use pager， 文档里写成use products了， pager用户不存在，所以3000访问没反应

**Comment by laispace** [comment]
@nupthale 感谢指出，已修改。
